### ISSUE TITLE
/usr/local/lib/libgmp.la: No such file or directory

### ISSUE THREAD

**Issue by jcubic** [spk121/guile-curl#6]
I have local copy of guile installed from source and when run make I got this errors:
```
/bin/grep: /usr/local/lib/libgmp.la: No such file or directory
/bin/sed: can't read /usr/local/lib/libgmp.la: No such file or directory
libtool:   error: '/usr/local/lib/libgmp.la' is not a valid libtool archive
```

I can install this library from source but how can I make `make` to use my local copy?

**Comment by spk121** [comment]
Well, this is an upstream issue, because guile-curl only depends on  guile and curl.  It is guile that depends on GMP.

If I recall correctly, when compiling Guile, one can add the environment variable LIBGMP_PREFIX= {include directory where the GMP header files are}, and one can add the environment variable LD_LIBRARY_PATH=/usr/local/lib

**Comment by jcubic** [comment]
Thanks for fast response, will try to install again with LIBGMP_PREFIX then.
